### ISSUE TITLE
"Restart build" on travis not visible

### ISSUE THREAD

**Issue by maartenbreddels** [conda-forge/vaex-feedstock#3]
I cannot restart a failed build (for instance when it took to long) on travis, the button is not there. However, I do see if for other conda-forge repos, just not for this one. @jakirkham ?

**Comment by jakirkham** [comment]
So you need to go to your account on Travis CI and run sync. After it runs you should see restart buttons and the like.

**Comment by maartenbreddels** [comment]
👍
